### PR TITLE
Add flags to specify generated struct and file names

### PR DESCRIPTION
**Pull request by pohang**
When a single mock is generated (non regex provided to -name),
can optionally specify -filename and/or -structname to override
the default names.

### CODE REVIEW

**Comment by kohago** [comment]
@pohang  Great! I just want to use that feature ASAP!

**Comment by freedemster** [comment]
This is a very useful feature, I would like to use it too.

**Comment by pdettori** [comment]
this is indeed a very useful feature ... any chance to get this PR moving forward ?

**Comment by LandonTClipp** [comment]
I think this is a great feature. Let's hold off on this until I can get CI auto-tagging. After that I will merge it.

**Pull request merged**
