### PR TITLE
Towards fixing #272

### LINKED ISSUE #272: improve go generate support
Having to do such thing is annoying:

```shell
➜  git git:(da-git-config-mock) ✗ go generate -n
docker run -v /home/blaggacao/go/src/github.com/git-town/git-town/src/git/../..:/src -w /src --user=$(`id-u`) vektra/mockery -dir=src/git -name ConfigurationInterface
➜  git git:(da-git-config-mock) ✗ go generate   
01 Jun 20 07:07 UTC INF Starting mockery version=2.0.0-alpha.2
01 Jun 20 07:07 UTC INF Walking version=2.0.0-alpha.2
01 Jun 20 07:07 UTC INF Generating mock interface=ConfigurationInterface path=mocks/ConfigurationInterface.go version=2.0.0-alpha.2
➜  git git:(da-git-config-mock) ✗ ls ../../mocks 
ConfigurationInterface.go
➜  git git:(da-git-config-mock) ✗ ls -la ../../mocks
total 32
drwxrwxr-x  2 blaggacao blaggacao  4096 Jun  1 02:07 .
drwxrwxr-x 16 blaggacao blaggacao  4096 Jun  1 01:39 ..
-rw-r--r--  1 root      root      16121 Jun  1 02:07 ConfigurationInterface.go
➜  git git:(da-git-config-mock) ✗ sudo chown $(id -u):$(id -g) -R ../../mocks
[sudo] password for blaggacao
```

while `$(id -u):$(id -g)` unfortunately isn't interpreted,
```shell
➜  git git:(da-git-config-mock) ✗ go generate -n                         
docker run -v /home/blaggacao/go/src/github.com/git-town/git-town/src/git/../..:/src -w /src --user=$(id -u):$(id -g) vektra/mockery -dir=src/git -name ConfigurationInterface
```

### PR DESCRIPTION
**Pull request by blaggacao**
@LandonTClipp I have no intimate knowledge o mockery, please check if it needs to write to other sites,  too. In my mind, this should fix #272.

### CODE REVIEW

**Comment by LandonTClipp** [comment]
Thanks for the PR @blaggacao. If you could build a local mockery image with this new line, test it works, and post the results here, we can merge this.

**Comment by blaggacao** [comment]
Without:
```shell
➜  git git:(da-git-config-mock) go generate 
02 Jun 20 16:24 UTC INF Starting mockery version=2.0.0-alpha.2
02 Jun 20 16:24 UTC INF Walking version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC ERR Error parsing file error="err: exit status 1: stderr: failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied\n" version=2.0.0-alpha.2
02 Jun 20 16:24 UTC FTL Unable to find 'ConfigurationInterface' in any go files under this path version=2.0.0-alpha.2
config.go:21: running "sh": exit status 1
```

**Comment by blaggacao** [comment]
Confirm it **didn't** work, mockery should not write the cache to `/`, but the very same working dir, instead.

**Comment by LandonTClipp** [comment]
I think the problem here is that mockery is installed to `/mockery` so `/` is its working directory.

**Pull request closed without merging**
