### PR TITLE
Fix generator support for variadic arguments

### PR DESCRIPTION
**Pull request by codeactual**
### Expected

1. Calls to `Mock` methods like `On/AssertCalled` allow tests to specify arguments, even variadic, just as they're written in the expected calls themselves.
1. `mock` features that rely on its diff logic, like `AnythingOfType`, should work with variadic arguments recorded by `mockery` via `Mock.Called`.

### Actual

1. Methods like `On` require the variadic argument values to be supplied as a slice. That requirement is inconsistent with how `mock` normally accepts variadic arguments in general.
1. `mock.AnythingOfType` does not seem to work with variadic arguments recorded as slices by `mockery`. It may indicate that any feature that relies on the `mock` diff logic are also incompatible. Examples of the problem are at the bottom of the PR.

### Changed

The generated mock methods now invoke `Mock.Called` with argument lists that always mirror the expected calls themselves, even for variadic arguments. This also restores compatibility with the diff logic in `mock`.

### Commit notes

- `generator.go`
  - Refactor `formatParamNames` function literal into a regular block because it only needs to be computed once
  - Add `generateCalled` method to keep `Generate` cleaner
  - Use a "golden file" for `TestGeneratorVariadicArgs` so it can also be imported in new `CompatSuite` 
  - Cover more variadic cases
- Add `CompatSuite` to host new variadic arg cases
- Fix typos to allow searching for variadic related code

#### Variadic args required to be slices for `Mock.On`

Contrived interface with an `Sprintf` method:

```
// ifaces/sprintfer.go
type Sprintfer interface {
    Sprintf(format string, a ...interface{}) string
}

// mocks/Sprintfer.go
func (_m *Sprintfer) Sprintf(format string, a ...interface{}) string {
    ret := _m.Called(format, a)

    var r0 string
    if rf, ok := ret.Get(0).(func(string, ...interface{}) string); ok {
            r0 = rf(format, a...)
    } else {
            r0 = ret.Get(0).(string)
    }

    return r0
}
```

Calling `Sprintf` with variadic args listed w/o a slice results in a test failure:

```
func TestSprintferPanic(t *testing.T) {
    m := new(mocks.Sprintfer)
    m.On("Sprintf", "int: %d string: %s", 22, "twenty two").Return("int: 22 string: twenty-two")
    m.Sprintf("int: %d string: %s", 22, "twenty two") // panic
}

mock: Unexpected Method Call
-----------------------------

Sprintf(string,[]interface {})
                0: "int: %d string: %s"
                1: []interface {}{22, "twenty two"}

The closest call I have is:

Sprintf(string,int,string)
                0: "int: %d string: %s"
                1: 22
                2: "twenty two"
```

#### `Mock.AnythingOfType` incompatibility

`TestAnythingOfType[1-5]` show attempts to use the feature with variadic args with different slice types and `AnythingOfType` values.

`TestAnythingOfType1` shows the most intuitive way to use the feature and passes with the patch applied.

```
func TestAnythingOfType1(t *testing.T) {
  m := new(mocks.Sprintfer)
  m.On("Sprintf", "int: %d string: %s", mock.AnythingOfType("int"), mock.AnythingOfType("string")).Return("int: 22 string: twenty-two")
  m.Sprintf("int: %d string: %s", 22, "twenty two")

  /*
  mock: Unexpected Method Call
  -----------------------------

  Sprintf(string,[]interface {})
          0: "int: %d string: %s"
          1: []interface {}{22, "twenty two"}

  The closest call I have is:

  Sprintf(string,mock.AnythingOfTypeArgument,mock.AnythingOfTypeArgument)
          0: "int: %d string: %s"
          1: "int"
          2: "string"
  */
}

func TestAnythingOfType2(t *testing.T) {
  m := new(mocks.Sprintfer)
  var expectedArgs []mock.AnythingOfTypeArgument
  expectedArgs = append(expectedArgs, mock.AnythingOfType("int"), mock.AnythingOfType("string"))
  m.On("Sprintf", "int: %d string: %s", expectedArgs).Return("int: 22 string: twenty-two")
  m.Sprintf("int: %d string: %s", 22, "twenty two")

  /*
  mock: Unexpected Method Call
  -----------------------------

  Sprintf(string,[]interface {})
          0: "int: %d string: %s"
          1: []interface {}{22, "twenty two"}

  The closest call I have is:

  Sprintf(string,[]mock.AnythingOfTypeArgument)
          0: "int: %d string: %s"
          1: []mock.AnythingOfTypeArgument{"int", "string"}
  */
}

func TestAnythingOfType3(t *testing.T) {
  m := new(mocks.Sprintfer)
  var expectedArgs []interface{}
  expectedArgs = append(expectedArgs, mock.AnythingOfType("int"), mock.AnythingOfType("string"))
  m.On("Sprintf", "int: %d string: %s", expectedArgs).Return("int: 22 string: twenty-two")
  m.Sprintf("int: %d string: %s", 22, "twenty two")

  /*
  mock: Unexpected Method Call
  -----------------------------

  Sprintf(string,[]interface {})
                0: "int: %d string: %s"
                1: []interface {}{22, "twenty two"}

  The closest call I have is:

  Sprintf(string,[]interface {})
        0: "int: %d string: %s"
        1: []interface {}{"int", "string"}

  Difference found in argument 1:

  --- Expected
  +++ Actual
  @@ -1,4 +1,4 @@
   ([]interface {}) (len=2) {
  - (int) 22,
  - (string) (len=10) "twenty two"
  + (mock.AnythingOfTypeArgument) (len=3) "int",
  + (mock.AnythingOfTypeArgument) (len=6) "string"
   }
  */
}

func TestAnythingOfType4(t *testing.T) {
  m := new(mocks.Sprintfer)
  var expectedArgs []interface{}
  expectedArgs = append(expectedArgs, mock.AnythingOfType("interface{}"), mock.AnythingOfType("interface{}"))
  m.On("Sprintf", "int: %d string: %s", expectedArgs).Return("int: 22 string: twenty-two")
  m.Sprintf("int: %d string: %s", 22, "twenty two")

  /*
  mock: Unexpected Method Call
  -----------------------------

  Sprintf(string,[]interface {})
          0: "int: %d string: %s"
          1: []interface {}{22, "twenty two"}

  The closest call I have is:

  Sprintf(string,[]interface {})
          0: "int: %d string: %s"
          1: []interface {}{"interface{}", "interface{}"}

  Difference found in argument 1:

  --- Expected
  +++ Actual
  @@ -1,4 +1,4 @@
   ([]interface {}) (len=2) {
  - (int) 22,
  - (string) (len=10) "twenty two"
  + (mock.AnythingOfTypeArgument) (len=11) "interface{}",
  + (mock.AnythingOfTypeArgument) (len=11) "interface{}"
   }
  */
}

func TestAnythingOfType5(t *testing.T) {
  m := new(mocks.Sprintfer)
  var expectedArgs []mock.AnythingOfTypeArgument
  expectedArgs = append(expectedArgs, mock.AnythingOfType("interface{}"), mock.AnythingOfType("interface{}"))
  m.On("Sprintf", "int: %d string: %s", expectedArgs).Return("int: 22 string: twenty-two")
  m.Sprintf("int: %d string: %s", 22, "twenty two")

  /*
  mock: Unexpected Method Call
  -----------------------------

  Sprintf(string,[]interface {})
          0: "int: %d string: %s"
          1: []interface {}{22, "twenty two"}

  The closest call I have is:

  Sprintf(string,[]mock.AnythingOfTypeArgument)
          0: "int: %d string: %s"
          1: []mock.AnythingOfTypeArgument{"interface{}", "interface{}"}
  */
}
```

### CODE REVIEW

**Comment by UberFarmer** [comment]
What's the recommended way now to mock a function that takes variadic args, if you don't care about how many args are used? I want something like this:

```go
func TestAnyArgs(t *testing.T) {
  m := new(mocks.Sprintfer)
  m.On(
    "Sprintf",
    mock.AnythingOfType("string"),
    mock.Anything,  // all variadic arguments
  ).Return("int: 22 string: twenty-two")
  m.Sprintf("int: %d string: %s", 22, "twenty two")
}
```

**Comment by codeactual** [comment]
Some examples:

```go
v.On("Sprintf", "int: %d string: %s", 22, "twenty two").Return("int: 22 string: twenty two")
v.On("Sprintf", "int: %d string: %s", mock.AnythingOfType("int"), mock.AnythingOfType("string")).Return("int: 22 string: twenty two"
```

In the case where the arguments to `On` will themselves be variable in the test, you'll need to do something like:

```go
var expectedArgs []interface{}
expectedArgs = append(expectedArgs, "int: %d string: %s", mock.AnythingOfType("int"), mock.AnythingOfType("string"))
v.On("Sprintf", expectedArgs...).Return("int: 22 string: twenty two")
```

Reminder: you won't be able to do this version (where the format string is a separate argument) ...

```go
var expectedArgs []interface{}
expectedArgs = append(expectedArgs, mock.AnythingOfType("int"), mock.AnythingOfType("string"))
v.On("Sprintf", "int: %d string: %s", expectedArgs...).Return("int: 22 string: twenty two")
```

... because it violates the signature of `On` and will result in an error from go like:

```
./variadic_test.go:119:6: too many arguments in call to v.Mock.On                                                                                                                    │On branch master
        have (string, string, []interface {}...)                                                                                                                                     │Changes not staged for commit:
        want (string, ...interface {})                                                                                                                                               │  (use "git add <file>..." to update what will be committed)
FAIL    command-line-arguments [build failed]     
```

**Comment by UberFarmer** [comment]
In the examples you provided you need to know exactly how many arguments the function will be called with in order to set up a mock.

I don't know how many arguments the function will be called with and I don't care -- in addition, in my use case, I'd like to set up a general mock to cover multiple calls with different numbers of args.

As a workaround, I could set up multiple mocks for all possible numbers of arguments but it feels bad

```go
variadicArgs := []interface{}{}
for i := 0; i < 10; i++ {
  m.On("Sprintf", mock.AnythingOfType("string"), variadicArgs...)
  append(variadicArgs, mock.Anything)
}
```

**Comment by orbiteleven** [comment]
@UberFarmer did you ever figure out a workaround for this?

**Pull request merged**
