### PR TITLE
Fix quiet flag

### PR DESCRIPTION
**Pull request by nmiyake**
Quiet flag implementation previously had issue where output would
bleed into generated file. Setting stdout to nil resolves the issue.

### CODE REVIEW

**Comment by nmiyake** [comment]
Tested locally to verify that this fixes the issue.

Writing a test for this would require doing a `go run` or compile-and-run of source as a separate process (since it has to do with redirecting the output of `stdout`). I can certainly write such a test, but it would involve a bit of overhead (create new temporary directory, create interface, do a `go run` on `main.go`, then verify output and clean up), so would want to make sure that such a test is desired/would be accepted before writing it.

**Comment by nmiyake** [comment]
@evanphx

**Comment by LandonTClipp** [comment]
Need to edit tests to get CI to pass.

**Comment by LandonTClipp** [comment]
This is going to be fixed by just simply letting all log output go to stderr, and anything else to stdout (if needed).

**Pull request closed without merging**
