### PR TITLE
Tell golint to ignore mockery output

### LINKED ISSUE #155: Prologue note creates lint artefacts
With the addition of the prologue note, the generated code no longer passes standard for godoc:

```
   Error  (GOLINT) GOLINT
    Package comment should be of the form "Package mocks ..."

    >>>        1 // Code generated by mockery v1.0.0
               2 package mocks
               3 
               4 import mock "github.com/stretchr/testify/mock"
```

I would suggest changing to:

    Package mocks contains mocks generated by mockery [version]

### PR DESCRIPTION
**Pull request by ejj**
The golint commit a5f4a24736 (Ignore generated code) causes it to
ignore files that begin with "Code generated" and end with "DO NOT
EDIT.".   By adding those lines to the prologue, we cause suppress
any warnings golint may flag on the generated code.  This patch also
adds an additional newline between the prologue and the Package
statement, which makes it clear to any other elements of the go
tool-chain that the prologue is not the package comment.

Fixes #155

### CODE REVIEW

**Comment by ejj** [comment]
Note I tested locally with golint and this does, indeed, resolve the problem.

**Comment by ejj** [comment]
Oops, updated the version, but not in the test.  Do you want the semantic version bumped for this, or should I leave it at 1.0.0?

**Comment by ejj** [comment]
Friendly bump =)

**Comment by tamccall** [comment]
LGTM. Make sure to link this pr from https://github.com/vektra/mockery/pull/156 just to be sure that there are not competing solutions.

**Comment by greysond** [comment]
Any chance this will be merged soon?

**Comment by ejj** [comment]
Friendly bump.

I think this is ready to be merged, but let me know if any other changes are necessary and I'm happy to make them.

Cheers

**Comment by evanphx** [comment]
This should be fixed by #169

**Pull request closed without merging**
