### PR TITLE
Vendoring external deps using glide

### PR DESCRIPTION
**Pull request by tamccall**

### CODE REVIEW

**Comment by codeactual** [comment]
If glide doesn't support vendor pruning [[1](https://github.com/golang/dep/issues/120), [2](https://github.com/golang/dep/pull/322)], it still might be worthwhile to do it via `find` in the `Makefile` ([example](https://github.com/golang/dep/pull/322#issue-213730765)) after each fetch.

This commit, and any future one to upgrade deps, will contain all sorts of files that aren't licenses or built (e.g. txt, javascript, etc.).

**Comment by andymc904** [comment]
@codeactual added a glide up target in the `Makefile` based off of the example you gave that will perform `glide up` and remove unnecessary files

**Comment by tamccall** [comment]
Ran into [this guy](https://github.com/sgotti/glide-vc) the other day would likely resolve @codeactual issues with unnecessary code in the vendor directory

**Comment by evanphx** [comment]
This is an oldie. I probably should vendor them but I'd do so with dep now instead.

**Pull request closed without merging**
