### PR TITLE
Fixed performance issue caused by loading config multiple times

### PR DESCRIPTION
**Pull request by andymc904**
Fixed  performance issues caused by loading config after every file load

See attached cpu profiles for more info on performance issues. 
Measured cpu profile on `make integration` in both cases
[cpu-profile.zip](https://github.com/vektra/mockery/files/871272/cpu-profile.zip)

Also fixes https://github.com/vektra/mockery/issues/104

### CODE REVIEW

**Comment by codeactual** [comment]
I think there are several opportunities to improve this for review-ability and scope.

- Remove as many file changes as possible which are not critical to the PR. GitHub says that 1,889 files were changed and 823,428 lines were added. A quick look at the manifest shows things like vendor tests, JS, and other non-Go code files.
- Consider splitting the `-cpuprofile` feature into a separate PR from the performance fix. I see how they were related in origin but they're easier to review apart.
- Package management seems endlessly controversial. I've used glide, worked well for me. But adoption of it might also fit better in its own PR that is only about packaging.

**Comment by andymc904** [comment]
Fair enough I'll just get the relevant changes in here.

But FWIW vendoring is something that should seriously be considered

**Comment by andymc904** [comment]
Added `cpuprofile` cli option PR https://github.com/vektra/mockery/pull/134

**Comment by andymc904** [comment]
Added issue to discuss preferred vendoring tools https://github.com/vektra/mockery/issues/135

**Pull request merged**
