### PR TITLE
Remove packages.NeedDeps

### PR DESCRIPTION
**Pull request by LandonTClipp**
This was introduced https://github.com/vektra/mockery/pull/435 but it wasn't the correct solution.

### CODE REVIEW

**Comment by emmanuel099** [comment]
Since ba1f213e177e70df3146e65b6e99731c9bf4faaa mock generation fails again with `Unexpected package creation during export data loading`

**Comment by emmanuel099** [comment]
Tested it with all versions since 2.10.0:

- v2.10.0: 
    - Fails with "internal error: package "context" without types was imported from ..." (using official binary)
    - Fails with "Unexpected package creation during export data loading" (using go install with golang 1.18)
- v2.10.1: Works
- v2.10.2: Works
- v2.10.3: Fails with "Unexpected package creation during export data loading"
- v2.10.4: Fails with "Unexpected package creation during export data loading"

**Comment by LandonTClipp** [comment]
Arg, I'm not sure why this isn't getting caught in the matrix test.

**Comment by LandonTClipp** [comment]
@emmanuel099 I am not able to replicate your issue on the latest build.

```
[lclipp@chilx-lcl1 testing-with-gomock][0] $ ls
doer  go.mod  LICENSE  match  mockery_2.10.4_Linux_x86_64.tar.gz  mocks  README.md  user
[lclipp@chilx-lcl1 testing-with-gomock][0] $ tar -xzf mockery_2.10.4_Linux_x86_64.tar.gz
[lclipp@chilx-lcl1 testing-with-gomock][0] $ ls
doer  go.mod  LICENSE  match  mockery  mockery_2.10.4_Linux_x86_64.tar.gz  mocks  README.md  user
[lclipp@chilx-lcl1 testing-with-gomock][0] $ ./mockery --version
07 Apr 22 18:49 CDT INF Starting mockery dry-run=false version=v2.10.4
v2.10.4
[lclipp@chilx-lcl1 testing-with-gomock][0] $ ./mockery --dir=doer --name=Doer
07 Apr 22 18:50 CDT INF Starting mockery dry-run=false version=v2.10.4
07 Apr 22 18:50 CDT INF Walking dry-run=false version=v2.10.4
07 Apr 22 18:50 CDT INF Generating mock dry-run=false interface=Doer qualified-name=github.com/sgreben/testing-with-gomock/doer version=v2.10.4
[lclipp@chilx-lcl1 testing-with-gomock][0] $ cat mocks/Doer.go
// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Doer is an autogenerated mock type for the Doer type
type Doer struct {
        mock.Mock
}

// DoSomething provides a mock function with given fields: _a0, _a1
func (_m *Doer) DoSomething(_a0 int, _a1 string) error {
        ret := _m.Called(_a0, _a1)

        var r0 error
        if rf, ok := ret.Get(0).(func(int, string) error); ok {
                r0 = rf(_a0, _a1)
        } else {
                r0 = ret.Error(0)
        }

        return r0
}
```

**Comment by comphilip** [comment]
@LandonTClipp `Unexpected package creation during export data loading` is `golang.org/x/tools` issue

https://github.com/golang/go/issues/51629

**Pull request merged**
