### PR TITLE
#11 Add nil check for pointer return types.

### PR DESCRIPTION
**Pull request by dakiva**

### CODE REVIEW

**Comment by evanphx** [comment]
Can you add/update the tests?

**Comment by dakiva** [comment]
@evanphx Good catch, I left out the tests, as there is a go panic when attempting to run TestGeneratorChanType.Perhaps, async.go is missing in fixtures? 

I pushed the changes to the two tests affected my pull request. go test still panics. (Also verified this without my changes).

**Comment by evanphx** [comment]
Oops! Good call, pushed that file.

On Tue, Mar 24, 2015 at 8:37 AM, Daniel Akiva <notifications@github.com>
wrote:

> @evanphx <https://github.com/evanphx> Good catch, I left out the tests,
> as there is a go panic when attempting to run
> TestGeneratorChanType.Perhaps, async.go is missing in fixtures?
>
> I pushed the changes to the two tests affected my pull request. go test
> still panics. (Also verified this without my changes).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vektra/mockery/pull/12#issuecomment-85563312>.
>



-- 
Evan Phoenix // evan@vektra.com

**Comment by dakiva** [comment]
@evanphx Thanks! Pulled & merged the changes - tests should pass.

**Comment by evanphx** [comment]
Thanks!

**Pull request merged**
