### PR TITLE
Towards #272

### PR DESCRIPTION
**Pull request by blaggacao**
This should reportedly fix it, wasn't able to properly build the docker image, though, to test. Sorry.

### CODE REVIEW

**Comment by LandonTClipp** [comment]
This makes more sense, thanks @blaggacao. Also when you say you couldn't build the docker image, what do you mean? Was there an error in this new Dockerfile?

**Comment by blaggacao** [comment]
@LandonTClipp I left a todo in the new e2e test with the problem...

**Comment by blaggacao** [comment]
@LandonTClipp My last commit hopefully solves this problem, if this breaks ci, please do the modifications needed...

**Comment by blaggacao** [comment]
Damn it! 
```shell
standard_init_linux.go:211: exec user process caused "no such file or directory"
make: *** [Makefile:24: integration] Error 1
```

**Pull request closed without merging**
