### PR TITLE
Ignore _test.go files in parser

### PR DESCRIPTION
**Pull request by tehleach**
Re-opening this PR on a branch so I can use my fork.

Following up on change in #102. #102 fixed **re**generating mocks with `_test` package in the same directory as the code when mocks exist, but if I then deleted all the mocks and tried to generate them "fresh", the mock generation failed because parser was still parsing all `.go` files in the directory **including** `_test.go` files.

I see that @IvanMalison had issue with #102 and said #93 should have fixed it, but I tried both the current version and I tried removing #102's change and neither worked when I had `package foo` and `package foo_test` in the same directory.

### CODE REVIEW

**Comment by dskarataev** [comment]
I also need this fix, please merge it

**Comment by tehleach** [comment]
Feel free to use [my fork](https://github.com/tehleach/mockery) (the master branch, not this PR branch) in the meantime @dskarataev, I'm not planning to make any further changes and it's working fine for my use case.

**Comment by dskarataev** [comment]
thanks @tehleach, yes I would use this option until it's merged to the original repo!

**Comment by tejasmanohar** [comment]
I also need this :)

**Comment by IvanMalison** [comment]
Can you guys clarify the reasons why you need this change? I don't understand the issue that is forcing you to do this.

**Comment by tejasmanohar** [comment]
I retraced my +1 comment. Due to the description of the issue, I thought this PR would fix mine, but it turns out my issue is slightly different-- https://github.com/vektra/mockery/issues/110 (though symptoms are similar).

**Comment by tehleach** [comment]
The issue is having a package with source code `foo` and a package with tests `foo_test`. In the same directory, and attempting to generate mocks in that directory. The test package caused mockery to be unable to generate my mocks. #102 allowed me to regenerate mocks in the same directory but when I tried to generate new mocks I wasn't able to - this change made it possible.

**Comment by IvanMalison** [comment]
Okay, so I guess the point is that you can't generate them the first time because they end up importing the mock, right

**Comment by tehleach** [comment]
Yeah, parse.go was attempting to read the test file before the mocks existed.

**Pull request merged**
