### PR TITLE
Implement go generate support

### PR DESCRIPTION
**Pull request by blaggacao**
Replaces #277  Atop #278

### CODE REVIEW

**Comment by blaggacao** [comment]
@LandonTClipp Confirm that added integration test from #278 are passing locally.

**Comment by blaggacao** [comment]
Fixes #272

**Comment by LandonTClipp** [comment]
@blaggacao are you okay with this being a part of the v2.0.0-alpha.* release? I can tag this but keep in mind that v2.0.0 will make changes to the CLI.

**Comment by blaggacao** [comment]
Yes, perfect! I already have the local built image for what I need in the meantime. Thanks!

**Pull request merged**
