### PR TITLE
Feature: ConfigDir Template

### LINKED ISSUE #802: mock generation for non-relative-to-interface dirs
Description
-------------

when the `dir` config is specified as not relative to the package (doesn't use `{{.InterfaceDir}}` template), the generation is relative to the current working directory rather than the project root (or wherever .mockery.yaml is specified).

Mockery Version
--------

2.42.1

Go Version
--------------

1.22.3

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. write an interface in a package (or set `.mockery.yaml` to mock an interface from an external go module, which is the use-case i'm encountering this issue), have `/mocks` directory exist in project root
2. set `dir` to `mocks` in `.mockery.yaml`, e.g.:
```yaml
with-expecter: true
dir: "mocks"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
packages:
  context:
    interfaces:
      Context:
```
4. run `mockery` in project root then `cd mocks` and run it again

### Expected Behavior

the second `mockery` shouldn't add any new files since config file was not changed between the two runs

### Actual Behavior

new mocks are created in `mocks/mocks`

### Proposal

add a new template that indicates the `.mockery.yaml` location, e.g. `{{.ConfigDir}}`

### PR DESCRIPTION
**Pull request by tobby-s**
Description
-------------

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

- Fixes #802 (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

Version of Go used when building/testing:
---------------------------------------------

- [x] 1.23

How Has This Been Tested?
---------------------------

haven't gotten around to learning how to build and run a branch. but this is a relatively simple change that's covered in unit test cases.

Checklist
-----------

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by LandonTClipp — APPROVED** [review]
This looks fine, I think we can merge it once the tests pass.

**Comment by tobby-s** [comment]
> This looks fine, I think we can merge it once the tests pass.

Could I clarify what this means?

**Comment by LandonTClipp** [comment]
The tests have passed so we can merge 😃

Sorry I have not been more responsive, I'll get this done tomorrow!

**Comment by tobby-s** [comment]
No worries 😅 I was just asking in case it was expected of contributors to build their branch and test, which I didn't have time for earlier

**Pull request merged**
