### PR TITLE
Add --inpackage-suffix option

### LINKED ISSUE #432: Make it configurable if the filename addition "mock" is prefixed or postfixed
When you have a folder like this

```
bar.go
bar_test.go
foo.go
foo_test.go
```

where the `foo.go` and `bar.go` contain a interface each the command

```
mockery --all --case=snake --inpackage
```

would create two mocks with the prefix `mock_`:

```
bar.go
bar_test.go
foo.go
foo_test.go
mock_bar.go
mock_foo.go
```

It would be nice to be in control if the additional `mock` string is prefixed or postfixed because it is often really nice to keep the files sorted together:

```
bar.go
bar_mock.go
bar_test.go
foo.go
foo_mock.go
foo_test.go
```

### PR DESCRIPTION
**Pull request by grongor**
This allows users to choose whether they prefer mock_name.go or name_mock.go for their filenames.

Description
-------------

I've seen this issue and it seemed like an easy pick, so here we are :D 

- Fixes #432

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Version of Golang used when building/testing:
---------------------------------------------

- [ ] 1.11
- [ ] 1.12
- [ ] 1.13
- [ ] 1.14
- [ ] 1.15
- [ ] 1.16
- [ ] 1.17
- [x] 1.18

How Has This Been Tested?
---------------------------

Run tests, tried `make mocks`, and it looks ok :)

### CODE REVIEW

**Comment by LandonTClipp** [comment]
Thanks for the PR, and the great contributions in general. For this particular one, I'm not super excited to field obscure requests that don't really affect the usability or functionality of the project, as that leads to bloat. If it became a highly requested feature it'd be a different story, but I'm leaning towards a pass for now.

**Comment by grongor** [comment]
Yeah, I can understand that. I'm personally not using the `--inpackage` option, so I don't really care, but I must say that if I wanted to use it, I'd definitely opt-in for the suffix (so that the relevant files are "close to each other").

**Review by FelipeBrizola — APPROVED** [review]

**Comment by YonitLopatinski** [comment]
Will this fix be merged??

**Comment by mgjules** [comment]
Can someone please merge it? or is there a blocking issue?

**Review by LandonTClipp — APPROVED** [review]
Only 10 months late, I'm deciding to approve this. Seems like enough people want this feature :)

**Pull request merged**
